apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: LoadBalancer
  ports:
    - name: goserver-service
      protocol: TCP
      port: 80 # Porta do servie
      targetPort: 8080 # Porta do container